[project]
name = "sound-pad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.11.3",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1"
]
